name: Next.js CI

on:
  push:
    branches:
      - master
      - "**"

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          check-latest: true

      - name: Install dependencies
        working-directory: ./website
        run: |
          npm install

      - name: Build and test the app
        working-directory: ./website
        run: |
          npm run build
          npm run test